### ISSUE TITLE
`devtool.py data checkout` uses unsupported password auth for `git clone`

### ISSUE THREAD

**Issue by curiousleo** [GermanZero-de/localzero-generator-core#216]
The key line is:

> Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.

```
$ python devtool.py data checkout
Looks like there is no checkout at all yet -- cloning for you
Cloning into 'public'...
[... succeeds ... ]
Cloning into 'proprietary'...
Username for 'https://github.com': curiousleo
Password for 'https://curiousleo@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/GermanZero-de/localzero-data-proprietary/'
Traceback (most recent call last):
  File "/home/leo/Code/localzero-generator-core/devtool.py", line 159, in <module>
    main()
  File "/home/leo/Code/localzero-generator-core/devtool.py", line 156, in main
    args.func(args)
  File "/home/leo/Code/localzero-generator-core/commands/cmd_data.py", line 203, in cmd_data_checkout
    refdatatools.clone(datadir, "proprietary", pa_token=args.pat)
  File "/home/leo/Code/localzero-generator-core/generatorcore/refdatatools.py", line 50, in clone
    subprocess.run(["git", "clone", url, repo], check=True, cwd=datadir)
  File "/nix/store/7mv9crg6y9bxgn39ynhkkwi3lhhsqhaj-python3-3.10.2/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/GermanZero-de/localzero-data-proprietary', 'proprietary']' returned non-zero exit status 128.
```

**Comment by curiousleo** [comment]
Workaround:

```
git clone git@github.com:GermanZero-de/localzero-data-proprietary.git data/proprietary
```

**Comment by bgrundmann** [comment]
Hmm I don’t think that this is fully true. That is I am pretty sure that I don’t use password authentication for GitHub and it just works (tm) for me. Probably my GitHub config differs from yours but I am in holidays without my laptop and hence can’t check before Sunday

**Comment by bgrundmann** [comment]
I could never reproduce this.

**Comment by curiousleo** [comment]
My best guess is that this line caused the issue I saw: https://github.com/GermanZero-de/localzero-generator-core/blob/2a2c49a49de859041e9f5508005114c9e449241b/src/climatevision/generator/refdatatools.py#L51

To reproduce it, it's probably necessary to delete the data directory locally so `clone()` gets called.
